name: MyWaypoints
main: pl.siepet.mywaypoints.MyWaypoints
version: 0.1.6
author: siepet
website: http://github.com/siepet
commands:
  waypoint:
    list: lists all waypoints
    add: adds waypoint
    edit: edits waypoint
    delete: deletes waypoint
    
